// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjgzfhnsyqwowbhpfatx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZ3pmaG5zeXF3b3diaHBmYXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTEzMDEsImV4cCI6MjA3MDcyNzMwMX0.gwSp4AI2IWeylAPO_SLyesc4-EP0pLl1Rwil9J3CDkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});